/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommentsView: typeof import('./src/components/CommentsView.vue')['default']
    DefaultView: typeof import('./src/components/DefaultView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PostForm: typeof import('./src/components/PostForm.vue')['default']
    PostView: typeof import('./src/components/PostView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
